{u'kind': u'qpxExpress#tripsSearch',
 u'trips': {u'data': {u'aircraft': [{u'code': u'332',
                                     u'kind': u'qpxexpress#aircraftData',
                                     u'name': u'Airbus A330'},
                                    {u'code': u'744',
                                     u'kind': u'qpxexpress#aircraftData',
                                     u'name': u'Boeing 747'},
                                    {u'code': u'77W',
                                     u'kind': u'qpxexpress#aircraftData',
                                     u'name': u'Boeing 777'}],
                      u'airport': [{u'city': u'NYC',
                                    u'code': u'JFK',
                                    u'kind': u'qpxexpress#airportData',
                                    u'name': u'New York John F Kennedy International'},
                                   {u'city': u'LON',
                                    u'code': u'LHR',
                                    u'kind': u'qpxexpress#airportData',
                                    u'name': u'London Heathrow'},
                                   {u'city': u'MOW',
                                    u'code': u'SVO',
                                    u'kind': u'qpxexpress#airportData',
                                    u'name': u'Moscow Sheremetyevo'}],
                      u'carrier': [{u'code': u'AY',
                                    u'kind': u'qpxexpress#carrierData',
                                    u'name': u'Finnair Oyj'},
                                   {u'code': u'BA',
                                    u'kind': u'qpxexpress#carrierData',
                                    u'name': u'British Airways p.l.c.'},
                                   {u'code': u'IB',
                                    u'kind': u'qpxexpress#carrierData',
                                    u'name': u'Iberia Lineas Aereas de Espana S.A.'},
                                   {u'code': u'SU',
                                    u'kind': u'qpxexpress#carrierData',
                                    u'name': u'PJSC "Aeroflot"'}],
                      u'city': [{u'code': u'LON',
                                 u'kind': u'qpxexpress#cityData',
                                 u'name': u'London'},
                                {u'code': u'MOW',
                                 u'kind': u'qpxexpress#cityData',
                                 u'name': u'Moscow'},
                                {u'code': u'NYC',
                                 u'kind': u'qpxexpress#cityData',
                                 u'name': u'New York'}],
                      u'kind': u'qpxexpress#data',
                      u'tax': [{u'id': u'XY',
                                u'kind': u'qpxexpress#taxData',
                                u'name': u'US Immigration Fee'},
                               {u'id': u'YQ_F',
                                u'kind': u'qpxexpress#taxData',
                                u'name': u'SU YQ surcharge'},
                               {u'id': u'AY_001',
                                u'kind': u'qpxexpress#taxData',
                                u'name': u'US September 11th Security Fee'},
                               {u'id': u'US_002',
                                u'kind': u'qpxexpress#taxData',
                                u'name': u'US International Departure Tax'},
                               {u'id': u'XA',
                                u'kind': u'qpxexpress#taxData',
                                u'name': u'USDA APHIS Fee'},
                               {u'id': u'YC',
                                u'kind': u'qpxexpress#taxData',
                                u'name': u'US Customs Fee'},
                               {u'id': u'YR_I',
                                u'kind': u'qpxexpress#taxData',
                                u'name': u'AY YR surcharge'},
                               {u'id': u'YQ_I',
                                u'kind': u'qpxexpress#taxData',
                                u'name': u'BA YQ surcharge'},
                               {u'id': u'UB',
                                u'kind': u'qpxexpress#taxData',
                                u'name': u'United Kingdom Passenger Service Charge'},
                               {u'id': u'XF',
                                u'kind': u'qpxexpress#taxData',
                                u'name': u'US Passenger Facility Charge'}]},
            u'kind': u'qpxexpress#tripOptions',
            u'requestId': u'WH7qdmrSOgSYS0kUM0OJbW',
            u'tripOption': [{u'id': u'COmQm89Ww2EREkhaG3kvH2006',
                             u'kind': u'qpxexpress#tripOption',
                             u'pricing': [{u'baseFareTotal': u'USD3165.00',
                                           u'fare': [{u'basisCode': u'H1N0O1CI',
                                                      u'carrier': u'BA',
                                                      u'destination': u'LON',
                                                      u'id': u'AEBFM/VqgdiXONmhAN5tCqoW6U6TkH5OLZNwBS8w8hBo',
                                                      u'kind': u'qpxexpress#fareInfo',
                                                      u'origin': u'NYC'},
                                                     {u'basisCode': u'BNRT',
                                                      u'carrier': u'SU',
                                                      u'destination': u'NYC',
                                                      u'id': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                      u'kind': u'qpxexpress#fareInfo',
                                                      u'origin': u'LON'}],
                                           u'fareCalculation': u'NYC BA LON M 1665.00H1N0O1CI SU X/MOW SU NYC 1500.00BNRT NUC 3165.00 END ROE 1.00 FARE USD 3165.00 XT 5.50YC 7.00XY 3.96XA 35.60US 5.60AY 45.20UB 382.90YQ 4.50XF JFK4.50',
                                           u'kind': u'qpxexpress#pricingInfo',
                                           u'latestTicketingTime': u'2016-05-14T23:59-04:00',
                                           u'passengers': {u'adultCount': 1,
                                                           u'kind': u'qpxexpress#passengerCounts'},
                                           u'ptc': u'ADT',
                                           u'refundable': True,
                                           u'saleFareTotal': u'USD3165.00',
                                           u'saleTaxTotal': u'USD490.26',
                                           u'saleTotal': u'USD3655.26',
                                           u'segmentPricing': [{u'fareId': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'G3iOJUwciy8UVMPC'},
                                                               {u'fareId': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'Gfgksmus4d0qDfug'},
                                                               {u'fareId': u'AEBFM/VqgdiXONmhAN5tCqoW6U6TkH5OLZNwBS8w8hBo',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'GOYy7R0z71Mgo9es'}],
                                           u'tax': [{u'chargeType': u'CARRIER_SURCHARGE',
                                                     u'code': u'YQ',
                                                     u'id': u'YQ_I',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD229.00'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'US',
                                                     u'country': u'US',
                                                     u'id': u'US_002',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD17.80'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'AY',
                                                     u'country': u'US',
                                                     u'id': u'AY_001',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD5.60'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XF',
                                                     u'country': u'US',
                                                     u'id': u'XF',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD4.50'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XA',
                                                     u'country': u'US',
                                                     u'id': u'XA',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD3.96'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XY',
                                                     u'country': u'US',
                                                     u'id': u'XY',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD7.00'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'YC',
                                                     u'country': u'US',
                                                     u'id': u'YC',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD5.50'},
                                                    {u'chargeType': u'CARRIER_SURCHARGE',
                                                     u'code': u'YQ',
                                                     u'id': u'YQ_F',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD153.90'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'US',
                                                     u'country': u'US',
                                                     u'id': u'US_002',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD17.80'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'UB',
                                                     u'country': u'GB',
                                                     u'id': u'UB',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD45.20'}]}],
                             u'saleTotal': u'USD3655.26',
                             u'slice': [{u'duration': 410,
                                         u'kind': u'qpxexpress#sliceInfo',
                                         u'segment': [{u'bookingCode': u'H',
                                                       u'bookingCodeCount': 9,
                                                       u'cabin': u'COACH',
                                                       u'duration': 410,
                                                       u'flight': {u'carrier': u'BA',
                                                                   u'number': u'178'},
                                                       u'id': u'GOYy7R0z71Mgo9es',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'744',
                                                                 u'arrivalTime': u'2016-06-11T19:50+01:00',
                                                                 u'departureTime': u'2016-06-11T08:00-04:00',
                                                                 u'destination': u'LHR',
                                                                 u'destinationTerminal': u'5',
                                                                 u'duration': 410,
                                                                 u'id': u'LRcVYP+t-I+20PDg',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Meal',
                                                                 u'mileage': 3440,
                                                                 u'origin': u'JFK',
                                                                 u'originTerminal': u'7',
                                                                 u'secure': True}],
                                                       u'marriedSegmentGroup': u'0'}]},
                                        {u'duration': 1445,
                                         u'kind': u'qpxexpress#sliceInfo',
                                         u'segment': [{u'bookingCode': u'B',
                                                       u'bookingCodeCount': 7,
                                                       u'cabin': u'COACH',
                                                       u'connectionDuration': 630,
                                                       u'duration': 220,
                                                       u'flight': {u'carrier': u'SU',
                                                                   u'number': u'2575'},
                                                       u'id': u'Gfgksmus4d0qDfug',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'332',
                                                                 u'arrivalTime': u'2016-06-12T03:55+03:00',
                                                                 u'departureTime': u'2016-06-11T22:15+01:00',
                                                                 u'destination': u'SVO',
                                                                 u'destinationTerminal': u'D',
                                                                 u'duration': 220,
                                                                 u'id': u'L6vonMuTHI2htmuT',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Dinner',
                                                                 u'mileage': 1557,
                                                                 u'origin': u'LHR',
                                                                 u'originTerminal': u'4'}],
                                                       u'marriedSegmentGroup': u'1'},
                                                      {u'bookingCode': u'B',
                                                       u'bookingCodeCount': 7,
                                                       u'cabin': u'COACH',
                                                       u'duration': 595,
                                                       u'flight': {u'carrier': u'SU',
                                                                   u'number': u'102'},
                                                       u'id': u'G3iOJUwciy8UVMPC',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'77W',
                                                                 u'arrivalTime': u'2016-06-12T17:20-04:00',
                                                                 u'departureTime': u'2016-06-12T14:25+03:00',
                                                                 u'destination': u'JFK',
                                                                 u'destinationTerminal': u'1',
                                                                 u'duration': 595,
                                                                 u'id': u'LxbGnSqD-5OEO736',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Lunch',
                                                                 u'mileage': 4646,
                                                                 u'origin': u'SVO',
                                                                 u'originTerminal': u'D',
                                                                 u'secure': True}],
                                                       u'marriedSegmentGroup': u'2'}]}]},
                            {u'id': u'COmQm89Ww2EREkhaG3kvH2004',
                             u'kind': u'qpxexpress#tripOption',
                             u'pricing': [{u'baseFareTotal': u'USD3165.00',
                                           u'fare': [{u'basisCode': u'H1N0O1C5',
                                                      u'carrier': u'AY',
                                                      u'destination': u'LON',
                                                      u'id': u'A2Aabx1bREAnIqPnzFMwSxL7jWFlzOWQDZvmNprupxzM',
                                                      u'kind': u'qpxexpress#fareInfo',
                                                      u'origin': u'NYC'},
                                                     {u'basisCode': u'BNRT',
                                                      u'carrier': u'SU',
                                                      u'destination': u'NYC',
                                                      u'id': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                      u'kind': u'qpxexpress#fareInfo',
                                                      u'origin': u'LON'}],
                                           u'fareCalculation': u'NYC AY LON M 1665.00H1N0O1C5 SU X/MOW SU NYC 1500.00BNRT NUC 3165.00 END ROE 1.00 FARE USD 3165.00 XT 5.50YC 7.00XY 3.96XA 35.60US 5.60AY 45.20UB 153.90YQ 229.00YR 4.50XF JFK4.50',
                                           u'kind': u'qpxexpress#pricingInfo',
                                           u'latestTicketingTime': u'2016-05-14T23:59-04:00',
                                           u'passengers': {u'adultCount': 1,
                                                           u'kind': u'qpxexpress#passengerCounts'},
                                           u'ptc': u'ADT',
                                           u'refundable': True,
                                           u'saleFareTotal': u'USD3165.00',
                                           u'saleTaxTotal': u'USD490.26',
                                           u'saleTotal': u'USD3655.26',
                                           u'segmentPricing': [{u'fareId': u'A2Aabx1bREAnIqPnzFMwSxL7jWFlzOWQDZvmNprupxzM',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'GnZ7TCmOsfLU-Xes'},
                                                               {u'fareId': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'G3iOJUwciy8UVMPC'},
                                                               {u'fareId': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'Gfgksmus4d0qDfug'}],
                                           u'tax': [{u'chargeType': u'CARRIER_SURCHARGE',
                                                     u'code': u'YR',
                                                     u'id': u'YR_I',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD229.00'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'US',
                                                     u'country': u'US',
                                                     u'id': u'US_002',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD17.80'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'AY',
                                                     u'country': u'US',
                                                     u'id': u'AY_001',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD5.60'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XF',
                                                     u'country': u'US',
                                                     u'id': u'XF',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD4.50'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XA',
                                                     u'country': u'US',
                                                     u'id': u'XA',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD3.96'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XY',
                                                     u'country': u'US',
                                                     u'id': u'XY',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD7.00'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'YC',
                                                     u'country': u'US',
                                                     u'id': u'YC',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD5.50'},
                                                    {u'chargeType': u'CARRIER_SURCHARGE',
                                                     u'code': u'YQ',
                                                     u'id': u'YQ_F',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD153.90'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'US',
                                                     u'country': u'US',
                                                     u'id': u'US_002',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD17.80'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'UB',
                                                     u'country': u'GB',
                                                     u'id': u'UB',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD45.20'}]}],
                             u'saleTotal': u'USD3655.26',
                             u'slice': [{u'duration': 410,
                                         u'kind': u'qpxexpress#sliceInfo',
                                         u'segment': [{u'bookingCode': u'H',
                                                       u'bookingCodeCount': 9,
                                                       u'cabin': u'COACH',
                                                       u'duration': 410,
                                                       u'flight': {u'carrier': u'AY',
                                                                   u'number': u'5478'},
                                                       u'id': u'GnZ7TCmOsfLU-Xes',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'744',
                                                                 u'arrivalTime': u'2016-06-11T19:50+01:00',
                                                                 u'departureTime': u'2016-06-11T08:00-04:00',
                                                                 u'destination': u'LHR',
                                                                 u'destinationTerminal': u'5',
                                                                 u'duration': 410,
                                                                 u'id': u'LRrtStNBpWJ81hal',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Meal',
                                                                 u'mileage': 3440,
                                                                 u'operatingDisclosure': u'OPERATED BY BRITISH AIRWAYS',
                                                                 u'origin': u'JFK',
                                                                 u'originTerminal': u'7',
                                                                 u'secure': True}],
                                                       u'marriedSegmentGroup': u'0'}]},
                                        {u'duration': 1445,
                                         u'kind': u'qpxexpress#sliceInfo',
                                         u'segment': [{u'bookingCode': u'B',
                                                       u'bookingCodeCount': 7,
                                                       u'cabin': u'COACH',
                                                       u'connectionDuration': 630,
                                                       u'duration': 220,
                                                       u'flight': {u'carrier': u'SU',
                                                                   u'number': u'2575'},
                                                       u'id': u'Gfgksmus4d0qDfug',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'332',
                                                                 u'arrivalTime': u'2016-06-12T03:55+03:00',
                                                                 u'departureTime': u'2016-06-11T22:15+01:00',
                                                                 u'destination': u'SVO',
                                                                 u'destinationTerminal': u'D',
                                                                 u'duration': 220,
                                                                 u'id': u'L6vonMuTHI2htmuT',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Dinner',
                                                                 u'mileage': 1557,
                                                                 u'origin': u'LHR',
                                                                 u'originTerminal': u'4'}],
                                                       u'marriedSegmentGroup': u'1'},
                                                      {u'bookingCode': u'B',
                                                       u'bookingCodeCount': 7,
                                                       u'cabin': u'COACH',
                                                       u'duration': 595,
                                                       u'flight': {u'carrier': u'SU',
                                                                   u'number': u'102'},
                                                       u'id': u'G3iOJUwciy8UVMPC',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'77W',
                                                                 u'arrivalTime': u'2016-06-12T17:20-04:00',
                                                                 u'departureTime': u'2016-06-12T14:25+03:00',
                                                                 u'destination': u'JFK',
                                                                 u'destinationTerminal': u'1',
                                                                 u'duration': 595,
                                                                 u'id': u'LxbGnSqD-5OEO736',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Lunch',
                                                                 u'mileage': 4646,
                                                                 u'origin': u'SVO',
                                                                 u'originTerminal': u'D',
                                                                 u'secure': True}],
                                                       u'marriedSegmentGroup': u'2'}]}]},
                            {u'id': u'COmQm89Ww2EREkhaG3kvH2001',
                             u'kind': u'qpxexpress#tripOption',
                             u'pricing': [{u'baseFareTotal': u'USD3165.00',
                                           u'fare': [{u'basisCode': u'H1N0O1C5',
                                                      u'carrier': u'AY',
                                                      u'destination': u'LON',
                                                      u'id': u'A2Aabx1bREAnIqPnzFMwSxL7jWFlzOWQDZvmNprupxzM',
                                                      u'kind': u'qpxexpress#fareInfo',
                                                      u'origin': u'NYC'},
                                                     {u'basisCode': u'BNRT',
                                                      u'carrier': u'SU',
                                                      u'destination': u'NYC',
                                                      u'id': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                      u'kind': u'qpxexpress#fareInfo',
                                                      u'origin': u'LON'}],
                                           u'fareCalculation': u'NYC AY LON M 1665.00H1N0O1C5 SU X/MOW SU NYC 1500.00BNRT NUC 3165.00 END ROE 1.00 FARE USD 3165.00 XT 5.50YC 7.00XY 3.96XA 35.60US 5.60AY 45.20UB 153.90YQ 229.00YR 4.50XF JFK4.50',
                                           u'kind': u'qpxexpress#pricingInfo',
                                           u'latestTicketingTime': u'2016-05-14T23:59-04:00',
                                           u'passengers': {u'adultCount': 1,
                                                           u'kind': u'qpxexpress#passengerCounts'},
                                           u'ptc': u'ADT',
                                           u'refundable': True,
                                           u'saleFareTotal': u'USD3165.00',
                                           u'saleTaxTotal': u'USD490.26',
                                           u'saleTotal': u'USD3655.26',
                                           u'segmentPricing': [{u'fareId': u'A2Aabx1bREAnIqPnzFMwSxL7jWFlzOWQDZvmNprupxzM',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'GnZ7TCmOsfLU-Xes'},
                                                               {u'fareId': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'Gfgksmus4d0qDfug'},
                                                               {u'fareId': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'GDuLWHLtExNmvVim'}],
                                           u'tax': [{u'chargeType': u'CARRIER_SURCHARGE',
                                                     u'code': u'YR',
                                                     u'id': u'YR_I',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD229.00'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'US',
                                                     u'country': u'US',
                                                     u'id': u'US_002',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD17.80'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'AY',
                                                     u'country': u'US',
                                                     u'id': u'AY_001',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD5.60'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XF',
                                                     u'country': u'US',
                                                     u'id': u'XF',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD4.50'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XA',
                                                     u'country': u'US',
                                                     u'id': u'XA',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD3.96'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XY',
                                                     u'country': u'US',
                                                     u'id': u'XY',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD7.00'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'YC',
                                                     u'country': u'US',
                                                     u'id': u'YC',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD5.50'},
                                                    {u'chargeType': u'CARRIER_SURCHARGE',
                                                     u'code': u'YQ',
                                                     u'id': u'YQ_F',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD153.90'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'US',
                                                     u'country': u'US',
                                                     u'id': u'US_002',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD17.80'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'UB',
                                                     u'country': u'GB',
                                                     u'id': u'UB',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD45.20'}]}],
                             u'saleTotal': u'USD3655.26',
                             u'slice': [{u'duration': 410,
                                         u'kind': u'qpxexpress#sliceInfo',
                                         u'segment': [{u'bookingCode': u'H',
                                                       u'bookingCodeCount': 9,
                                                       u'cabin': u'COACH',
                                                       u'duration': 410,
                                                       u'flight': {u'carrier': u'AY',
                                                                   u'number': u'5478'},
                                                       u'id': u'GnZ7TCmOsfLU-Xes',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'744',
                                                                 u'arrivalTime': u'2016-06-11T19:50+01:00',
                                                                 u'departureTime': u'2016-06-11T08:00-04:00',
                                                                 u'destination': u'LHR',
                                                                 u'destinationTerminal': u'5',
                                                                 u'duration': 410,
                                                                 u'id': u'LRrtStNBpWJ81hal',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Meal',
                                                                 u'mileage': 3440,
                                                                 u'operatingDisclosure': u'OPERATED BY BRITISH AIRWAYS',
                                                                 u'origin': u'JFK',
                                                                 u'originTerminal': u'7',
                                                                 u'secure': True}],
                                                       u'marriedSegmentGroup': u'0'}]},
                                        {u'duration': 1150,
                                         u'kind': u'qpxexpress#sliceInfo',
                                         u'segment': [{u'bookingCode': u'B',
                                                       u'bookingCodeCount': 7,
                                                       u'cabin': u'COACH',
                                                       u'connectionDuration': 345,
                                                       u'duration': 220,
                                                       u'flight': {u'carrier': u'SU',
                                                                   u'number': u'2575'},
                                                       u'id': u'Gfgksmus4d0qDfug',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'332',
                                                                 u'arrivalTime': u'2016-06-12T03:55+03:00',
                                                                 u'departureTime': u'2016-06-11T22:15+01:00',
                                                                 u'destination': u'SVO',
                                                                 u'destinationTerminal': u'D',
                                                                 u'duration': 220,
                                                                 u'id': u'L6vonMuTHI2htmuT',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Dinner',
                                                                 u'mileage': 1557,
                                                                 u'origin': u'LHR',
                                                                 u'originTerminal': u'4'}],
                                                       u'marriedSegmentGroup': u'1'},
                                                      {u'bookingCode': u'B',
                                                       u'bookingCodeCount': 7,
                                                       u'cabin': u'COACH',
                                                       u'duration': 585,
                                                       u'flight': {u'carrier': u'SU',
                                                                   u'number': u'100'},
                                                       u'id': u'GDuLWHLtExNmvVim',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'77W',
                                                                 u'arrivalTime': u'2016-06-12T12:25-04:00',
                                                                 u'departureTime': u'2016-06-12T09:40+03:00',
                                                                 u'destination': u'JFK',
                                                                 u'destinationTerminal': u'1',
                                                                 u'duration': 585,
                                                                 u'id': u'LFJshLhvOr4qg4EL',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Lunch',
                                                                 u'mileage': 4646,
                                                                 u'origin': u'SVO',
                                                                 u'originTerminal': u'D',
                                                                 u'secure': True}],
                                                       u'marriedSegmentGroup': u'2'}]}]},
                            {u'id': u'COmQm89Ww2EREkhaG3kvH2003',
                             u'kind': u'qpxexpress#tripOption',
                             u'pricing': [{u'baseFareTotal': u'USD3165.00',
                                           u'fare': [{u'basisCode': u'H1N0O1CI',
                                                      u'carrier': u'BA',
                                                      u'destination': u'LON',
                                                      u'id': u'AEBFM/VqgdiXONmhAN5tCqoW6U6TkH5OLZNwBS8w8hBo',
                                                      u'kind': u'qpxexpress#fareInfo',
                                                      u'origin': u'NYC'},
                                                     {u'basisCode': u'BNRT',
                                                      u'carrier': u'SU',
                                                      u'destination': u'NYC',
                                                      u'id': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                      u'kind': u'qpxexpress#fareInfo',
                                                      u'origin': u'LON'}],
                                           u'fareCalculation': u'NYC BA LON M 1665.00H1N0O1CI SU X/MOW SU NYC 1500.00BNRT NUC 3165.00 END ROE 1.00 FARE USD 3165.00 XT 5.50YC 7.00XY 3.96XA 35.60US 5.60AY 45.20UB 382.90YQ 4.50XF JFK4.50',
                                           u'kind': u'qpxexpress#pricingInfo',
                                           u'latestTicketingTime': u'2016-05-14T23:59-04:00',
                                           u'passengers': {u'adultCount': 1,
                                                           u'kind': u'qpxexpress#passengerCounts'},
                                           u'ptc': u'ADT',
                                           u'refundable': True,
                                           u'saleFareTotal': u'USD3165.00',
                                           u'saleTaxTotal': u'USD490.26',
                                           u'saleTotal': u'USD3655.26',
                                           u'segmentPricing': [{u'fareId': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'Gfgksmus4d0qDfug'},
                                                               {u'fareId': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'GDuLWHLtExNmvVim'},
                                                               {u'fareId': u'AEBFM/VqgdiXONmhAN5tCqoW6U6TkH5OLZNwBS8w8hBo',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'GOYy7R0z71Mgo9es'}],
                                           u'tax': [{u'chargeType': u'CARRIER_SURCHARGE',
                                                     u'code': u'YQ',
                                                     u'id': u'YQ_I',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD229.00'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'US',
                                                     u'country': u'US',
                                                     u'id': u'US_002',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD17.80'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'AY',
                                                     u'country': u'US',
                                                     u'id': u'AY_001',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD5.60'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XF',
                                                     u'country': u'US',
                                                     u'id': u'XF',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD4.50'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XA',
                                                     u'country': u'US',
                                                     u'id': u'XA',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD3.96'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XY',
                                                     u'country': u'US',
                                                     u'id': u'XY',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD7.00'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'YC',
                                                     u'country': u'US',
                                                     u'id': u'YC',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD5.50'},
                                                    {u'chargeType': u'CARRIER_SURCHARGE',
                                                     u'code': u'YQ',
                                                     u'id': u'YQ_F',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD153.90'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'US',
                                                     u'country': u'US',
                                                     u'id': u'US_002',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD17.80'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'UB',
                                                     u'country': u'GB',
                                                     u'id': u'UB',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD45.20'}]}],
                             u'saleTotal': u'USD3655.26',
                             u'slice': [{u'duration': 410,
                                         u'kind': u'qpxexpress#sliceInfo',
                                         u'segment': [{u'bookingCode': u'H',
                                                       u'bookingCodeCount': 9,
                                                       u'cabin': u'COACH',
                                                       u'duration': 410,
                                                       u'flight': {u'carrier': u'BA',
                                                                   u'number': u'178'},
                                                       u'id': u'GOYy7R0z71Mgo9es',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'744',
                                                                 u'arrivalTime': u'2016-06-11T19:50+01:00',
                                                                 u'departureTime': u'2016-06-11T08:00-04:00',
                                                                 u'destination': u'LHR',
                                                                 u'destinationTerminal': u'5',
                                                                 u'duration': 410,
                                                                 u'id': u'LRcVYP+t-I+20PDg',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Meal',
                                                                 u'mileage': 3440,
                                                                 u'origin': u'JFK',
                                                                 u'originTerminal': u'7',
                                                                 u'secure': True}],
                                                       u'marriedSegmentGroup': u'0'}]},
                                        {u'duration': 1150,
                                         u'kind': u'qpxexpress#sliceInfo',
                                         u'segment': [{u'bookingCode': u'B',
                                                       u'bookingCodeCount': 7,
                                                       u'cabin': u'COACH',
                                                       u'connectionDuration': 345,
                                                       u'duration': 220,
                                                       u'flight': {u'carrier': u'SU',
                                                                   u'number': u'2575'},
                                                       u'id': u'Gfgksmus4d0qDfug',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'332',
                                                                 u'arrivalTime': u'2016-06-12T03:55+03:00',
                                                                 u'departureTime': u'2016-06-11T22:15+01:00',
                                                                 u'destination': u'SVO',
                                                                 u'destinationTerminal': u'D',
                                                                 u'duration': 220,
                                                                 u'id': u'L6vonMuTHI2htmuT',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Dinner',
                                                                 u'mileage': 1557,
                                                                 u'origin': u'LHR',
                                                                 u'originTerminal': u'4'}],
                                                       u'marriedSegmentGroup': u'1'},
                                                      {u'bookingCode': u'B',
                                                       u'bookingCodeCount': 7,
                                                       u'cabin': u'COACH',
                                                       u'duration': 585,
                                                       u'flight': {u'carrier': u'SU',
                                                                   u'number': u'100'},
                                                       u'id': u'GDuLWHLtExNmvVim',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'77W',
                                                                 u'arrivalTime': u'2016-06-12T12:25-04:00',
                                                                 u'departureTime': u'2016-06-12T09:40+03:00',
                                                                 u'destination': u'JFK',
                                                                 u'destinationTerminal': u'1',
                                                                 u'duration': 585,
                                                                 u'id': u'LFJshLhvOr4qg4EL',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Lunch',
                                                                 u'mileage': 4646,
                                                                 u'origin': u'SVO',
                                                                 u'originTerminal': u'D',
                                                                 u'secure': True}],
                                                       u'marriedSegmentGroup': u'2'}]}]},
                            {u'id': u'COmQm89Ww2EREkhaG3kvH2005',
                             u'kind': u'qpxexpress#tripOption',
                             u'pricing': [{u'baseFareTotal': u'USD3165.00',
                                           u'fare': [{u'basisCode': u'H1N0O1C5',
                                                      u'carrier': u'IB',
                                                      u'destination': u'LON',
                                                      u'id': u'AUQwwtsgLiB6bCtemoCBcViaWO6c6ZS9Z7a/YkYEKK3I',
                                                      u'kind': u'qpxexpress#fareInfo',
                                                      u'origin': u'NYC'},
                                                     {u'basisCode': u'BNRT',
                                                      u'carrier': u'SU',
                                                      u'destination': u'NYC',
                                                      u'id': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                      u'kind': u'qpxexpress#fareInfo',
                                                      u'origin': u'LON'}],
                                           u'fareCalculation': u'NYC IB LON M 1665.00H1N0O1C5 SU X/MOW SU NYC 1500.00BNRT NUC 3165.00 END ROE 1.00 FARE USD 3165.00 XT 5.50YC 7.00XY 3.96XA 35.60US 5.60AY 45.20UB 382.90YQ 4.50XF JFK4.50',
                                           u'kind': u'qpxexpress#pricingInfo',
                                           u'latestTicketingTime': u'2016-05-14T23:59-04:00',
                                           u'passengers': {u'adultCount': 1,
                                                           u'kind': u'qpxexpress#passengerCounts'},
                                           u'ptc': u'ADT',
                                           u'refundable': True,
                                           u'saleFareTotal': u'USD3165.00',
                                           u'saleTaxTotal': u'USD490.26',
                                           u'saleTotal': u'USD3655.26',
                                           u'segmentPricing': [{u'fareId': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'G3iOJUwciy8UVMPC'},
                                                               {u'fareId': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'Gfgksmus4d0qDfug'},
                                                               {u'fareId': u'AUQwwtsgLiB6bCtemoCBcViaWO6c6ZS9Z7a/YkYEKK3I',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'GtKuk3sCb+Jt9T1m'}],
                                           u'tax': [{u'chargeType': u'CARRIER_SURCHARGE',
                                                     u'code': u'YQ',
                                                     u'id': u'YQ_I',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD229.00'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'US',
                                                     u'country': u'US',
                                                     u'id': u'US_002',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD17.80'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'AY',
                                                     u'country': u'US',
                                                     u'id': u'AY_001',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD5.60'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XF',
                                                     u'country': u'US',
                                                     u'id': u'XF',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD4.50'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XA',
                                                     u'country': u'US',
                                                     u'id': u'XA',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD3.96'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XY',
                                                     u'country': u'US',
                                                     u'id': u'XY',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD7.00'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'YC',
                                                     u'country': u'US',
                                                     u'id': u'YC',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD5.50'},
                                                    {u'chargeType': u'CARRIER_SURCHARGE',
                                                     u'code': u'YQ',
                                                     u'id': u'YQ_F',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD153.90'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'US',
                                                     u'country': u'US',
                                                     u'id': u'US_002',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD17.80'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'UB',
                                                     u'country': u'GB',
                                                     u'id': u'UB',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD45.20'}]}],
                             u'saleTotal': u'USD3655.26',
                             u'slice': [{u'duration': 410,
                                         u'kind': u'qpxexpress#sliceInfo',
                                         u'segment': [{u'bookingCode': u'H',
                                                       u'bookingCodeCount': 9,
                                                       u'cabin': u'COACH',
                                                       u'duration': 410,
                                                       u'flight': {u'carrier': u'IB',
                                                                   u'number': u'4618'},
                                                       u'id': u'GtKuk3sCb+Jt9T1m',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'744',
                                                                 u'arrivalTime': u'2016-06-11T19:50+01:00',
                                                                 u'departureTime': u'2016-06-11T08:00-04:00',
                                                                 u'destination': u'LHR',
                                                                 u'destinationTerminal': u'5',
                                                                 u'duration': 410,
                                                                 u'id': u'LSIjH9oZdfkuRuSf',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'mileage': 3440,
                                                                 u'operatingDisclosure': u'OPERATED BY BRITISH AIRWAYS',
                                                                 u'origin': u'JFK',
                                                                 u'originTerminal': u'7',
                                                                 u'secure': True}],
                                                       u'marriedSegmentGroup': u'0'}]},
                                        {u'duration': 1445,
                                         u'kind': u'qpxexpress#sliceInfo',
                                         u'segment': [{u'bookingCode': u'B',
                                                       u'bookingCodeCount': 7,
                                                       u'cabin': u'COACH',
                                                       u'connectionDuration': 630,
                                                       u'duration': 220,
                                                       u'flight': {u'carrier': u'SU',
                                                                   u'number': u'2575'},
                                                       u'id': u'Gfgksmus4d0qDfug',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'332',
                                                                 u'arrivalTime': u'2016-06-12T03:55+03:00',
                                                                 u'departureTime': u'2016-06-11T22:15+01:00',
                                                                 u'destination': u'SVO',
                                                                 u'destinationTerminal': u'D',
                                                                 u'duration': 220,
                                                                 u'id': u'L6vonMuTHI2htmuT',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Dinner',
                                                                 u'mileage': 1557,
                                                                 u'origin': u'LHR',
                                                                 u'originTerminal': u'4'}],
                                                       u'marriedSegmentGroup': u'1'},
                                                      {u'bookingCode': u'B',
                                                       u'bookingCodeCount': 7,
                                                       u'cabin': u'COACH',
                                                       u'duration': 595,
                                                       u'flight': {u'carrier': u'SU',
                                                                   u'number': u'102'},
                                                       u'id': u'G3iOJUwciy8UVMPC',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'77W',
                                                                 u'arrivalTime': u'2016-06-12T17:20-04:00',
                                                                 u'departureTime': u'2016-06-12T14:25+03:00',
                                                                 u'destination': u'JFK',
                                                                 u'destinationTerminal': u'1',
                                                                 u'duration': 595,
                                                                 u'id': u'LxbGnSqD-5OEO736',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Lunch',
                                                                 u'mileage': 4646,
                                                                 u'origin': u'SVO',
                                                                 u'originTerminal': u'D',
                                                                 u'secure': True}],
                                                       u'marriedSegmentGroup': u'2'}]}]},
                            {u'id': u'COmQm89Ww2EREkhaG3kvH2002',
                             u'kind': u'qpxexpress#tripOption',
                             u'pricing': [{u'baseFareTotal': u'USD3165.00',
                                           u'fare': [{u'basisCode': u'H1N0O1C5',
                                                      u'carrier': u'IB',
                                                      u'destination': u'LON',
                                                      u'id': u'AUQwwtsgLiB6bCtemoCBcViaWO6c6ZS9Z7a/YkYEKK3I',
                                                      u'kind': u'qpxexpress#fareInfo',
                                                      u'origin': u'NYC'},
                                                     {u'basisCode': u'BNRT',
                                                      u'carrier': u'SU',
                                                      u'destination': u'NYC',
                                                      u'id': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                      u'kind': u'qpxexpress#fareInfo',
                                                      u'origin': u'LON'}],
                                           u'fareCalculation': u'NYC IB LON M 1665.00H1N0O1C5 SU X/MOW SU NYC 1500.00BNRT NUC 3165.00 END ROE 1.00 FARE USD 3165.00 XT 5.50YC 7.00XY 3.96XA 35.60US 5.60AY 45.20UB 382.90YQ 4.50XF JFK4.50',
                                           u'kind': u'qpxexpress#pricingInfo',
                                           u'latestTicketingTime': u'2016-05-14T23:59-04:00',
                                           u'passengers': {u'adultCount': 1,
                                                           u'kind': u'qpxexpress#passengerCounts'},
                                           u'ptc': u'ADT',
                                           u'refundable': True,
                                           u'saleFareTotal': u'USD3165.00',
                                           u'saleTaxTotal': u'USD490.26',
                                           u'saleTotal': u'USD3655.26',
                                           u'segmentPricing': [{u'fareId': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'Gfgksmus4d0qDfug'},
                                                               {u'fareId': u'AwzELZQfVwKUCdLbS2mWIQetwkYE1yo2WfOVtI7U',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'GDuLWHLtExNmvVim'},
                                                               {u'fareId': u'AUQwwtsgLiB6bCtemoCBcViaWO6c6ZS9Z7a/YkYEKK3I',
                                                                u'kind': u'qpxexpress#segmentPricing',
                                                                u'segmentId': u'GtKuk3sCb+Jt9T1m'}],
                                           u'tax': [{u'chargeType': u'CARRIER_SURCHARGE',
                                                     u'code': u'YQ',
                                                     u'id': u'YQ_I',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD229.00'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'US',
                                                     u'country': u'US',
                                                     u'id': u'US_002',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD17.80'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'AY',
                                                     u'country': u'US',
                                                     u'id': u'AY_001',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD5.60'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XF',
                                                     u'country': u'US',
                                                     u'id': u'XF',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD4.50'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XA',
                                                     u'country': u'US',
                                                     u'id': u'XA',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD3.96'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'XY',
                                                     u'country': u'US',
                                                     u'id': u'XY',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD7.00'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'YC',
                                                     u'country': u'US',
                                                     u'id': u'YC',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD5.50'},
                                                    {u'chargeType': u'CARRIER_SURCHARGE',
                                                     u'code': u'YQ',
                                                     u'id': u'YQ_F',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD153.90'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'US',
                                                     u'country': u'US',
                                                     u'id': u'US_002',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD17.80'},
                                                    {u'chargeType': u'GOVERNMENT',
                                                     u'code': u'UB',
                                                     u'country': u'GB',
                                                     u'id': u'UB',
                                                     u'kind': u'qpxexpress#taxInfo',
                                                     u'salePrice': u'USD45.20'}]}],
                             u'saleTotal': u'USD3655.26',
                             u'slice': [{u'duration': 410,
                                         u'kind': u'qpxexpress#sliceInfo',
                                         u'segment': [{u'bookingCode': u'H',
                                                       u'bookingCodeCount': 9,
                                                       u'cabin': u'COACH',
                                                       u'duration': 410,
                                                       u'flight': {u'carrier': u'IB',
                                                                   u'number': u'4618'},
                                                       u'id': u'GtKuk3sCb+Jt9T1m',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'744',
                                                                 u'arrivalTime': u'2016-06-11T19:50+01:00',
                                                                 u'departureTime': u'2016-06-11T08:00-04:00',
                                                                 u'destination': u'LHR',
                                                                 u'destinationTerminal': u'5',
                                                                 u'duration': 410,
                                                                 u'id': u'LSIjH9oZdfkuRuSf',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'mileage': 3440,
                                                                 u'operatingDisclosure': u'OPERATED BY BRITISH AIRWAYS',
                                                                 u'origin': u'JFK',
                                                                 u'originTerminal': u'7',
                                                                 u'secure': True}],
                                                       u'marriedSegmentGroup': u'0'}]},
                                        {u'duration': 1150,
                                         u'kind': u'qpxexpress#sliceInfo',
                                         u'segment': [{u'bookingCode': u'B',
                                                       u'bookingCodeCount': 7,
                                                       u'cabin': u'COACH',
                                                       u'connectionDuration': 345,
                                                       u'duration': 220,
                                                       u'flight': {u'carrier': u'SU',
                                                                   u'number': u'2575'},
                                                       u'id': u'Gfgksmus4d0qDfug',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'332',
                                                                 u'arrivalTime': u'2016-06-12T03:55+03:00',
                                                                 u'departureTime': u'2016-06-11T22:15+01:00',
                                                                 u'destination': u'SVO',
                                                                 u'destinationTerminal': u'D',
                                                                 u'duration': 220,
                                                                 u'id': u'L6vonMuTHI2htmuT',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Dinner',
                                                                 u'mileage': 1557,
                                                                 u'origin': u'LHR',
                                                                 u'originTerminal': u'4'}],
                                                       u'marriedSegmentGroup': u'1'},
                                                      {u'bookingCode': u'B',
                                                       u'bookingCodeCount': 7,
                                                       u'cabin': u'COACH',
                                                       u'duration': 585,
                                                       u'flight': {u'carrier': u'SU',
                                                                   u'number': u'100'},
                                                       u'id': u'GDuLWHLtExNmvVim',
                                                       u'kind': u'qpxexpress#segmentInfo',
                                                       u'leg': [{u'aircraft': u'77W',
                                                                 u'arrivalTime': u'2016-06-12T12:25-04:00',
                                                                 u'departureTime': u'2016-06-12T09:40+03:00',
                                                                 u'destination': u'JFK',
                                                                 u'destinationTerminal': u'1',
                                                                 u'duration': 585,
                                                                 u'id': u'LFJshLhvOr4qg4EL',
                                                                 u'kind': u'qpxexpress#legInfo',
                                                                 u'meal': u'Lunch',
                                                                 u'mileage': 4646,
                                                                 u'origin': u'SVO',
                                                                 u'originTerminal': u'D',
                                                                 u'secure': True}],
                                                       u'marriedSegmentGroup': u'2'}]}]}]}}