[{u'kind': u'qpxExpress#tripsSearch',
   u'trips': {u'data': {u'aircraft': [{u'code': u'32S',
                                       u'kind': u'qpxexpress#aircraftData',
                                       u'name': u'Airbus A320'}],
                        u'airport': [{u'city': u'NYC',
                                      u'code': u'JFK',
                                      u'kind': u'qpxexpress#airportData',
                                      u'name': u'New York John F Kennedy International'},
                                     {u'city': u'SFO',
                                      u'code': u'SFO',
                                      u'kind': u'qpxexpress#airportData',
                                      u'name': u'San Francisco International'}],
                        u'carrier': [{u'code': u'B6',
                                      u'kind': u'qpxexpress#carrierData',
                                      u'name': u'Jetblue Airways Corporation'}],
                        u'city': [{u'code': u'NYC',
                                   u'kind': u'qpxexpress#cityData',
                                   u'name': u'New York'},
                                  {u'code': u'SFO',
                                   u'kind': u'qpxexpress#cityData',
                                   u'name': u'San Francisco'}],
                        u'kind': u'qpxexpress#data',
                        u'tax': [{u'id': u'ZP',
                                  u'kind': u'qpxexpress#taxData',
                                  u'name': u'US Flight Segment Tax'},
                                 {u'id': u'AY_001',
                                  u'kind': u'qpxexpress#taxData',
                                  u'name': u'US September 11th Security Fee'},
                                 {u'id': u'US_001',
                                  u'kind': u'qpxexpress#taxData',
                                  u'name': u'US Transportation Tax'},
                                 {u'id': u'XF',
                                  u'kind': u'qpxexpress#taxData',
                                  u'name': u'US Passenger Facility Charge'}]},v
              u'kind': u'qpxexpress#tripOptions',
              u'requestId': u'bzJkXmWwHuw2gZd430OLyX',
              u'tripOption': [{u'id': u'Juj2Mzs4afIMFIXN5YyhE8001',
                               u'kind': u'qpxexpress#tripOption',
                               u'pricing': [{u'baseFareTotal': u'USD397.21',
                                             u'fare': [{u'basisCode': u'ZH2ABEN',
                                                        u'carrier': u'B6',
                                                        u'destination': u'NYC',
                                                        u'id': u'AY53iUBBQPajkTs6VnRz5y6Y9PRxvV7d6qfnYL5rTFK2',
                                                        u'kind': u'qpxexpress#fareInfo',
                                                        u'origin': u'SFO'},
                                                       {u'basisCode': u'OH2AUEN5',
                                                        u'carrier': u'B6',
                                                        u'destination': u'SFO',
                                                        u'id': u'AEte7xLnujCIZ7aV6Qs/yrZtykGMx2eAhtvKHCISCVQKRPUEDuDuG5saqCrbmkGdLsYhTFP7HMIl4UcunVRgt+3e7muS7WXsizrW9QFFKUympHu2CPqifG5Bx9pyWUw1rIdh2wmNCT0jZX/',
                                                        u'kind': u'qpxexpress#fareInfo',
                                                        u'origin': u'NYC',
                                                        u'private': True}],
                                             u'fareCalculation': u'SFO B6 NYC 207.44ZH2ABEN B6 SFO 189.77OH2AUEN5 USD 397.21 END ZP SFO JFK XT 29.79US 8.00ZP 5.60AY 9.00XF SFO4.50 JFK4.50',
                                             u'kind': u'qpxexpress#pricingInfo',
                                             u'latestTicketingTime': u'2016-05-18T23:59-04:00',
                                             u'passengers': {u'adultCount': 1,
                                                             u'kind': u'qpxexpress#passengerCounts'},
                                             u'ptc': u'ADT',
                                             u'saleFareTotal': u'USD397.21',
                                             u'saleTaxTotal': u'USD52.39',
                                             u'saleTotal': u'USD449.60',
                                             u'segmentPricing': [{u'fareId': u'AEte7xLnujCIZ7aV6Qs/yrZtykGMx2eAhtvKHCISCVQKRPUEDuDuG5saqCrbmkGdLsYhTFP7HMIl4UcunVRgt+3e7muS7WXsizrW9QFFKUympHu2CPqifG5Bx9pyWUw1rIdh2wmNCT0jZX/',
                                                                  u'kind': u'qpxexpress#segmentPricing',
                                                                  u'segmentId': u'GjuuL7Bz2H07intQ'},
                                                                 {u'fareId': u'AY53iUBBQPajkTs6VnRz5y6Y9PRxvV7d6qfnYL5rTFK2',
                                                                  u'kind': u'qpxexpress#segmentPricing',
                                                                  u'segmentId': u'GzqOFgdv5JKb3XvS'}],
                                             u'tax': [{u'chargeType': u'GOVERNMENT',
                                                       u'code': u'US',
                                                       u'country': u'US',
                                                       u'id': u'US_001',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD29.79'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'AY',
                                                       u'country': u'US',
                                                       u'id': u'AY_001',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD5.60'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'XF',
                                                       u'country': u'US',
                                                       u'id': u'XF',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD9.00'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'ZP',
                                                       u'country': u'US',
                                                       u'id': u'ZP',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD8.00'}]}],
                               u'saleTotal': u'USD449.60',
                               u'slice': [{u'duration': 338,
                                           u'kind': u'qpxexpress#sliceInfo',
                                           u'segment': [{u'bookingCode': u'Z',
                                                         u'bookingCodeCount': 1,
                                                         u'cabin': u'COACH',
                                                         u'duration': 338,
                                                         u'flight': {u'carrier': u'B6',
                                                                     u'number': u'16'},
                                                         u'id': u'GzqOFgdv5JKb3XvS',
                                                         u'kind': u'qpxexpress#segmentInfo',
                                                         u'leg': [{u'aircraft': u'32S',
                                                                   u'arrivalTime': u'2016-07-11T15:38-04:00',
                                                                   u'departureTime': u'2016-07-11T07:00-07:00',
                                                                   u'destination': u'JFK',
                                                                   u'destinationTerminal': u'5',
                                                                   u'duration': 338,
                                                                   u'id': u'LfsWxiEinrnBGHaw',
                                                                   u'kind': u'qpxexpress#legInfo',
                                                                   u'meal': u'Meal',
                                                                   u'mileage': 2579,
                                                                   u'onTimePerformance': 90,
                                                                   u'origin': u'SFO',
                                                                   u'originTerminal': u'I',
                                                                   u'secure': True}],
                                                         u'marriedSegmentGroup': u'0'}]},
                                          {u'duration': 398,
                                           u'kind': u'qpxexpress#sliceInfo',
                                           u'segment': [{u'bookingCode': u'O',
                                                         u'bookingCodeCount': 7,
                                                         u'cabin': u'COACH',
                                                         u'duration': 398,
                                                         u'flight': {u'carrier': u'B6',
                                                                     u'number': u'1415'},
                                                         u'id': u'GjuuL7Bz2H07intQ',
                                                         u'kind': u'qpxexpress#segmentInfo',
                                                         u'leg': [{u'aircraft': u'32S',
                                                                   u'arrivalTime': u'2016-07-11T21:48-07:00',
                                                                   u'departureTime': u'2016-07-11T18:10-04:00',
                                                                   u'destination': u'SFO',
                                                                   u'destinationTerminal': u'I',
                                                                   u'duration': 398,
                                                                   u'id': u'LxtSSNiyfygiMKZJ',
                                                                   u'kind': u'qpxexpress#legInfo',
                                                                   u'meal': u'Meal',
                                                                   u'mileage': 2579,
                                                                   u'origin': u'JFK',
                                                                   u'originTerminal': u'5',
                                                                   u'secure': True}],
                                                         u'marriedSegmentGroup': u'1'}]}]},
                              {u'id': u'Juj2Mzs4afIMFIXN5YyhE8002',
                               u'kind': u'qpxexpress#tripOption',
                               u'pricing': [{u'baseFareTotal': u'USD397.21',
                                             u'fare': [{u'basisCode': u'ZH2ABEN',
                                                        u'carrier': u'B6',
                                                        u'destination': u'NYC',
                                                        u'id': u'AY53iUBBQPajkTs6VnRz5y6Y9PRxvV7d6qfnYL5rTFK2',
                                                        u'kind': u'qpxexpress#fareInfo',
                                                        u'origin': u'SFO'},
                                                       {u'basisCode': u'OH2AUEN5',
                                                        u'carrier': u'B6',
                                                        u'destination': u'SFO',
                                                        u'id': u'AEte7xLnujCIZ7aV6Qs/yrZtykGMx2eAhtvKHCISCVQKRPUEDuDuG5saqCrbmkGdLsYhTFP7HMIl4UcunVRgt+3e7muS7WXsizrW9QFFKUympHu2CPqifG5Bx9pyWUw1rIdh2wmNCT0jZX/',
                                                        u'kind': u'qpxexpress#fareInfo',
                                                        u'origin': u'NYC',
                                                        u'private': True}],
                                             u'fareCalculation': u'SFO B6 NYC 207.44ZH2ABEN B6 SFO 189.77OH2AUEN5 USD 397.21 END ZP SFO JFK XT 29.79US 8.00ZP 11.20AY 9.00XF SFO4.50 JFK4.50',
                                             u'kind': u'qpxexpress#pricingInfo',
                                             u'latestTicketingTime': u'2016-05-18T23:59-04:00',
                                             u'passengers': {u'adultCount': 1,
                                                             u'kind': u'qpxexpress#passengerCounts'},
                                             u'ptc': u'ADT',
                                             u'saleFareTotal': u'USD397.21',
                                             u'saleTaxTotal': u'USD57.99',
                                             u'saleTotal': u'USD455.20',
                                             u'segmentPricing': [{u'fareId': u'AY53iUBBQPajkTs6VnRz5y6Y9PRxvV7d6qfnYL5rTFK2',
                                                                  u'kind': u'qpxexpress#segmentPricing',
                                                                  u'segmentId': u'GzqOFgdv5JKb3XvS'},
                                                                 {u'fareId': u'AEte7xLnujCIZ7aV6Qs/yrZtykGMx2eAhtvKHCISCVQKRPUEDuDuG5saqCrbmkGdLsYhTFP7HMIl4UcunVRgt+3e7muS7WXsizrW9QFFKUympHu2CPqifG5Bx9pyWUw1rIdh2wmNCT0jZX/',
                                                                  u'kind': u'qpxexpress#segmentPricing',
                                                                  u'segmentId': u'GW8n+hTBSDAMZ6qM'}],
                                             u'tax': [{u'chargeType': u'GOVERNMENT',
                                                       u'code': u'US',
                                                       u'country': u'US',
                                                       u'id': u'US_001',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD29.79'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'AY',
                                                       u'country': u'US',
                                                       u'id': u'AY_001',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD11.20'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'XF',
                                                       u'country': u'US',
                                                       u'id': u'XF',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD9.00'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'ZP',
                                                       u'country': u'US',
                                                       u'id': u'ZP',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD8.00'}]}],
                               u'saleTotal': u'USD455.20',
                               u'slice': [{u'duration': 338,
                                           u'kind': u'qpxexpress#sliceInfo',
                                           u'segment': [{u'bookingCode': u'Z',
                                                         u'bookingCodeCount': 1,
                                                         u'cabin': u'COACH',
                                                         u'duration': 338,
                                                         u'flight': {u'carrier': u'B6',
                                                                     u'number': u'16'},
                                                         u'id': u'GzqOFgdv5JKb3XvS',
                                                         u'kind': u'qpxexpress#segmentInfo',
                                                         u'leg': [{u'aircraft': u'32S',
                                                                   u'arrivalTime': u'2016-07-11T15:38-04:00',
                                                                   u'departureTime': u'2016-07-11T07:00-07:00',
                                                                   u'destination': u'JFK',
                                                                   u'destinationTerminal': u'5',
                                                                   u'duration': 338,
                                                                   u'id': u'LfsWxiEinrnBGHaw',
                                                                   u'kind': u'qpxexpress#legInfo',
                                                                   u'meal': u'Meal',
                                                                   u'mileage': 2579,
                                                                   u'onTimePerformance': 90,
                                                                   u'origin': u'SFO',
                                                                   u'originTerminal': u'I',
                                                                   u'secure': True}],
                                                         u'marriedSegmentGroup': u'0'}]},
                                          {u'duration': 390,
                                           u'kind': u'qpxexpress#sliceInfo',
                                           u'segment': [{u'bookingCode': u'O',
                                                         u'bookingCodeCount': 1,
                                                         u'cabin': u'COACH',
                                                         u'duration': 390,
                                                         u'flight': {u'carrier': u'B6',
                                                                     u'number': u'1715'},
                                                         u'id': u'GW8n+hTBSDAMZ6qM',
                                                         u'kind': u'qpxexpress#segmentInfo',
                                                         u'leg': [{u'aircraft': u'32S',
                                                                   u'arrivalTime': u'2016-07-12T00:50-07:00',
                                                                   u'departureTime': u'2016-07-11T21:20-04:00',
                                                                   u'destination': u'SFO',
                                                                   u'destinationTerminal': u'I',
                                                                   u'duration': 390,
                                                                   u'id': u'L8lFoOjHnRvVsGwT',
                                                                   u'kind': u'qpxexpress#legInfo',
                                                                   u'meal': u'Meal',
                                                                   u'mileage': 2579,
                                                                   u'onTimePerformance': 70,
                                                                   u'origin': u'JFK',
                                                                   u'originTerminal': u'5',
                                                                   u'secure': True}],
                                                         u'marriedSegmentGroup': u'1'}]}]}]}},
  {u'kind': u'qpxExpress#tripsSearch',
   u'trips': {u'data': {u'aircraft': [{u'code': u'32S',
                                       u'kind': u'qpxexpress#aircraftData',
                                       u'name': u'Airbus A320'}],
                        u'airport': [{u'city': u'NYC',
                                      u'code': u'JFK',
                                      u'kind': u'qpxexpress#airportData',
                                      u'name': u'New York John F Kennedy International'},
                                     {u'city': u'LAX',
                                      u'code': u'LAX',
                                      u'kind': u'qpxexpress#airportData',
                                      u'name': u'Los Angeles International'}],
                        u'carrier': [{u'code': u'B6',
                                      u'kind': u'qpxexpress#carrierData',
                                      u'name': u'Jetblue Airways Corporation'}],
                        u'city': [{u'code': u'LAX',
                                   u'kind': u'qpxexpress#cityData',
                                   u'name': u'Los Angeles'},
                                  {u'code': u'NYC',
                                   u'kind': u'qpxexpress#cityData',
                                   u'name': u'New York'}],
                        u'kind': u'qpxexpress#data',
                        u'tax': [{u'id': u'ZP',
                                  u'kind': u'qpxexpress#taxData',
                                  u'name': u'US Flight Segment Tax'},
                                 {u'id': u'AY_001',
                                  u'kind': u'qpxexpress#taxData',
                                  u'name': u'US September 11th Security Fee'},
                                 {u'id': u'US_001',
                                  u'kind': u'qpxexpress#taxData',
                                  u'name': u'US Transportation Tax'},
                                 {u'id': u'XF',
                                  u'kind': u'qpxexpress#taxData',
                                  u'name': u'US Passenger Facility Charge'}]},
              u'kind': u'qpxexpress#tripOptions',
              u'requestId': u'KcmzHRj2KowfZ9Czd0OLyX',
              u'tripOption': [{u'id': u'czSfIFePYdLQuZ5CMKfseV001',
                               u'kind': u'qpxexpress#tripOption',
                               u'pricing': [{u'baseFareTotal': u'USD440.93',
                                             u'fare': [{u'basisCode': u'ZH4AUEN5',
                                                        u'carrier': u'B6',
                                                        u'destination': u'NYC',
                                                        u'id': u'A7msgNPkVMgw+qTh4rGuVvFOGjb+cixFh/kRY5J0hPQMwS96IqTRistXSTeIg1zC1cDeMHo1V6IPBp/PVVmDAONl6ChYsyRZBGPJgLIMEpSPsv3iRu71RBImKkVvPTcAUFDfKCEINVKubuo',
                                                        u'kind': u'qpxexpress#fareInfo',
                                                        u'origin': u'LAX',
                                                        u'private': True},
                                                       {u'basisCode': u'MH4ABEN',
                                                        u'carrier': u'B6',
                                                        u'destination': u'LAX',
                                                        u'id': u'ANgd1wvCu6ENAYSx2W6LTpDZKVC/jB127HLBXiUQO3Vo',
                                                        u'kind': u'qpxexpress#fareInfo',
                                                        u'origin': u'NYC'}],
                                             u'fareCalculation': u'LAX B6 NYC 213.02ZH4AUEN5 B6 LAX 227.91MH4ABEN USD 440.93 END ZP LAX JFK XT 33.07US 8.00ZP 11.20AY 9.00XF LAX4.50 JFK4.50',
                                             u'kind': u'qpxexpress#pricingInfo',
                                             u'latestTicketingTime': u'2016-05-18T23:59-04:00',
                                             u'passengers': {u'adultCount': 1,
                                                             u'kind': u'qpxexpress#passengerCounts'},
                                             u'ptc': u'ADT',
                                             u'saleFareTotal': u'USD440.93',
                                             u'saleTaxTotal': u'USD61.27',
                                             u'saleTotal': u'USD502.20',
                                             u'segmentPricing': [{u'fareId': u'ANgd1wvCu6ENAYSx2W6LTpDZKVC/jB127HLBXiUQO3Vo',
                                                                  u'kind': u'qpxexpress#segmentPricing',
                                                                  u'segmentId': u'G5b0HDy2qrHqkKH2'},
                                                                 {u'fareId': u'A7msgNPkVMgw+qTh4rGuVvFOGjb+cixFh/kRY5J0hPQMwS96IqTRistXSTeIg1zC1cDeMHo1V6IPBp/PVVmDAONl6ChYsyRZBGPJgLIMEpSPsv3iRu71RBImKkVvPTcAUFDfKCEINVKubuo',
                                                                  u'kind': u'qpxexpress#segmentPricing',
                                                                  u'segmentId': u'GQ-H2bI3wCGOCrTU'}],
                                             u'tax': [{u'chargeType': u'GOVERNMENT',
                                                       u'code': u'US',
                                                       u'country': u'US',
                                                       u'id': u'US_001',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD33.07'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'AY',
                                                       u'country': u'US',
                                                       u'id': u'AY_001',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD11.20'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'XF',
                                                       u'country': u'US',
                                                       u'id': u'XF',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD9.00'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'ZP',
                                                       u'country': u'US',
                                                       u'id': u'ZP',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD8.00'}]}],
                               u'saleTotal': u'USD502.20',
                               u'slice': [{u'duration': 330,
                                           u'kind': u'qpxexpress#sliceInfo',
                                           u'segment': [{u'bookingCode': u'Z',
                                                         u'bookingCodeCount': 1,
                                                         u'cabin': u'COACH',
                                                         u'duration': 330,
                                                         u'flight': {u'carrier': u'B6',
                                                                     u'number': u'224'},
                                                         u'id': u'GQ-H2bI3wCGOCrTU',
                                                         u'kind': u'qpxexpress#segmentInfo',
                                                         u'leg': [{u'aircraft': u'32S',
                                                                   u'arrivalTime': u'2016-07-11T18:15-04:00',
                                                                   u'departureTime': u'2016-07-11T09:45-07:00',
                                                                   u'destination': u'JFK',
                                                                   u'destinationTerminal': u'5',
                                                                   u'duration': 330,
                                                                   u'id': u'LfFS71XgAR054YrW',
                                                                   u'kind': u'qpxexpress#legInfo',
                                                                   u'meal': u'Meal',
                                                                   u'mileage': 2468,
                                                                   u'origin': u'LAX',
                                                                   u'originTerminal': u'3',
                                                                   u'secure': True}],
                                                         u'marriedSegmentGroup': u'0'}]},
                                          {u'duration': 358,
                                           u'kind': u'qpxexpress#sliceInfo',
                                           u'segment': [{u'bookingCode': u'M',
                                                         u'bookingCodeCount': 7,
                                                         u'cabin': u'COACH',
                                                         u'duration': 358,
                                                         u'flight': {u'carrier': u'B6',
                                                                     u'number': u'2023'},
                                                         u'id': u'G5b0HDy2qrHqkKH2',
                                                         u'kind': u'qpxexpress#segmentInfo',
                                                         u'leg': [{u'aircraft': u'32S',
                                                                   u'arrivalTime': u'2016-07-12T01:43-07:00',
                                                                   u'departureTime': u'2016-07-11T22:45-04:00',
                                                                   u'destination': u'LAX',
                                                                   u'destinationTerminal': u'3',
                                                                   u'duration': 358,
                                                                   u'id': u'LpwLPvtyUy1AUR6+',
                                                                   u'kind': u'qpxexpress#legInfo',
                                                                   u'meal': u'Meal',
                                                                   u'mileage': 2468,
                                                                   u'onTimePerformance': 70,
                                                                   u'origin': u'JFK',
                                                                   u'originTerminal': u'5',
                                                                   u'secure': True}],
                                                         u'marriedSegmentGroup': u'1'}]}]},
                              {u'id': u'czSfIFePYdLQuZ5CMKfseV002',
                               u'kind': u'qpxexpress#tripOption',
                               u'pricing': [{u'baseFareTotal': u'USD455.82',
                                             u'fare': [{u'basisCode': u'MH4ABEN',
                                                        u'carrier': u'B6',
                                                        u'destination': u'NYC',
                                                        u'id': u'ANgd1wvCu6ENAYSx2W6LTpDZKVC/jB127HLBXiUQO3Vo',
                                                        u'kind': u'qpxexpress#fareInfo',
                                                        u'origin': u'LAX'},
                                                       {u'basisCode': u'MH4ABEN',
                                                        u'carrier': u'B6',
                                                        u'destination': u'LAX',
                                                        u'id': u'ANgd1wvCu6ENAYSx2W6LTpDZKVC/jB127HLBXiUQO3Vo',
                                                        u'kind': u'qpxexpress#fareInfo',
                                                        u'origin': u'NYC'}],
                                             u'fareCalculation': u'LAX B6 NYC 227.91MH4ABEN B6 LAX 227.91MH4ABEN USD 455.82 END ZP LAX JFK XT 34.18US 8.00ZP 5.60AY 9.00XF LAX4.50 JFK4.50',
                                             u'kind': u'qpxexpress#pricingInfo',
                                             u'latestTicketingTime': u'2016-05-18T23:59-04:00',
                                             u'passengers': {u'adultCount': 1,
                                                             u'kind': u'qpxexpress#passengerCounts'},
                                             u'ptc': u'ADT',
                                             u'saleFareTotal': u'USD455.82',
                                             u'saleTaxTotal': u'USD56.78',
                                             u'saleTotal': u'USD512.60',
                                             u'segmentPricing': [{u'fareId': u'ANgd1wvCu6ENAYSx2W6LTpDZKVC/jB127HLBXiUQO3Vo',
                                                                  u'kind': u'qpxexpress#segmentPricing',
                                                                  u'segmentId': u'G5b0HDy2qrHqkKH2'},
                                                                 {u'fareId': u'ANgd1wvCu6ENAYSx2W6LTpDZKVC/jB127HLBXiUQO3Vo',
                                                                  u'kind': u'qpxexpress#segmentPricing',
                                                                  u'segmentId': u'G3WGJt7LCRt-iKGL'}],
                                             u'tax': [{u'chargeType': u'GOVERNMENT',
                                                       u'code': u'US',
                                                       u'country': u'US',
                                                       u'id': u'US_001',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD34.18'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'AY',
                                                       u'country': u'US',
                                                       u'id': u'AY_001',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD5.60'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'XF',
                                                       u'country': u'US',
                                                       u'id': u'XF',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD9.00'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'ZP',
                                                       u'country': u'US',
                                                       u'id': u'ZP',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD8.00'}]}],
                               u'saleTotal': u'USD512.60',
                               u'slice': [{u'duration': 330,
                                           u'kind': u'qpxexpress#sliceInfo',
                                           u'segment': [{u'bookingCode': u'M',
                                                         u'bookingCodeCount': 7,
                                                         u'cabin': u'COACH',
                                                         u'duration': 330,
                                                         u'flight': {u'carrier': u'B6',
                                                                     u'number': u'324'},
                                                         u'id': u'G3WGJt7LCRt-iKGL',
                                                         u'kind': u'qpxexpress#segmentInfo',
                                                         u'leg': [{u'aircraft': u'32S',
                                                                   u'arrivalTime': u'2016-07-11T20:05-04:00',
                                                                   u'departureTime': u'2016-07-11T11:35-07:00',
                                                                   u'destination': u'JFK',
                                                                   u'destinationTerminal': u'5',
                                                                   u'duration': 330,
                                                                   u'id': u'L97q2yalL-8c1Ld9',
                                                                   u'kind': u'qpxexpress#legInfo',
                                                                   u'meal': u'Meal',
                                                                   u'mileage': 2468,
                                                                   u'onTimePerformance': 90,
                                                                   u'origin': u'LAX',
                                                                   u'originTerminal': u'3',
                                                                   u'secure': True}],
                                                         u'marriedSegmentGroup': u'0'}]},
                                          {u'duration': 358,
                                           u'kind': u'qpxexpress#sliceInfo',
                                           u'segment': [{u'bookingCode': u'M',
                                                         u'bookingCodeCount': 7,
                                                         u'cabin': u'COACH',
                                                         u'duration': 358,
                                                         u'flight': {u'carrier': u'B6',
                                                                     u'number': u'2023'},
                                                         u'id': u'G5b0HDy2qrHqkKH2',
                                                         u'kind': u'qpxexpress#segmentInfo',
                                                         u'leg': [{u'aircraft': u'32S',
                                                                   u'arrivalTime': u'2016-07-12T01:43-07:00',
                                                                   u'departureTime': u'2016-07-11T22:45-04:00',
                                                                   u'destination': u'LAX',
                                                                   u'destinationTerminal': u'3',
                                                                   u'duration': 358,
                                                                   u'id': u'LpwLPvtyUy1AUR6+',
                                                                   u'kind': u'qpxexpress#legInfo',
                                                                   u'meal': u'Meal',
                                                                   u'mileage': 2468,
                                                                   u'onTimePerformance': 70,
                                                                   u'origin': u'JFK',
                                                                   u'originTerminal': u'5',
                                                                   u'secure': True}],
                                                         u'marriedSegmentGroup': u'1'}]}]}]}},
  {u'kind': u'qpxExpress#tripsSearch',
   u'trips': {u'data': {u'aircraft': [{u'code': u'320',
                                       u'kind': u'qpxexpress#aircraftData',
                                       u'name': u'Airbus A320'},
                                      {u'code': u'E90',
                                       u'kind': u'qpxexpress#aircraftData',
                                       u'name': u'Embraer RJ-190'}],
                        u'airport': [{u'city': u'NYC',
                                      u'code': u'JFK',
                                      u'kind': u'qpxexpress#airportData',
                                      u'name': u'New York John F Kennedy International'},
                                     {u'city': u'CHI',
                                      u'code': u'ORD',
                                      u'kind': u'qpxexpress#airportData',
                                      u'name': u"Chicago O'Hare"}],
                        u'carrier': [{u'code': u'B6',
                                      u'kind': u'qpxexpress#carrierData',
                                      u'name': u'Jetblue Airways Corporation'}],
                        u'city': [{u'code': u'CHI',
                                   u'kind': u'qpxexpress#cityData',
                                   u'name': u'Chicago'},
                                  {u'code': u'NYC',
                                   u'kind': u'qpxexpress#cityData',
                                   u'name': u'New York'}],
                        u'kind': u'qpxexpress#data',
                        u'tax': [{u'id': u'ZP',
                                  u'kind': u'qpxexpress#taxData',
                                  u'name': u'US Flight Segment Tax'},
                                 {u'id': u'AY_001',
                                  u'kind': u'qpxexpress#taxData',
                                  u'name': u'US September 11th Security Fee'},
                                 {u'id': u'US_001',
                                  u'kind': u'qpxexpress#taxData',
                                  u'name': u'US Transportation Tax'},
                                 {u'id': u'XF',
                                  u'kind': u'qpxexpress#taxData',
                                  u'name': u'US Passenger Facility Charge'}]},
              u'kind': u'qpxexpress#tripOptions',
              u'requestId': u'23oti1Z0pmppFH1CM0OLyX',
              u'tripOption': [{u'id': u'394f2mM2ryTQs7DAQNSBLU002',
                               u'kind': u'qpxexpress#tripOption',
                               u'pricing': [{u'baseFareTotal': u'USD241.86',
                                             u'fare': [{u'basisCode': u'MH4ADEN',
                                                        u'carrier': u'B6',
                                                        u'destination': u'NYC',
                                                        u'id': u'AWQSZKg4WdIzjGRe9MxuCxp1HWx5y2Qhb7p9up7xqYeM',
                                                        u'kind': u'qpxexpress#fareInfo',
                                                        u'origin': u'CHI'},
                                                       {u'basisCode': u'UI7ABEN5',
                                                        u'carrier': u'B6',
                                                        u'destination': u'CHI',
                                                        u'id': u'AKV4tAev5WkcuYs1T6b/8AzAKbhBsj2BFQ3lFlCpM1xsjfFdSJDYe71xva4Zg0AAmdUZ3TxLWCkitnpx8KmtCrkvUfeQdDQM30FuH6DmkfY+eYvY98D7uB4CVwp18RKyhJKs9hgYq0dfAx/',
                                                        u'kind': u'qpxexpress#fareInfo',
                                                        u'origin': u'NYC',
                                                        u'private': True}],
                                             u'fareCalculation': u'CHI B6 JFK 146.98MH4ADEN B6 CHI 94.88UI7ABEN5 USD 241.86 END ZP ORD JFK XT 18.14US 8.00ZP 11.20AY 9.00XF ORD4.50 JFK4.50',
                                             u'kind': u'qpxexpress#pricingInfo',
                                             u'latestTicketingTime': u'2016-05-18T23:59-04:00',
                                             u'passengers': {u'adultCount': 1,
                                                             u'kind': u'qpxexpress#passengerCounts'},
                                             u'ptc': u'ADT',
                                             u'saleFareTotal': u'USD241.86',
                                             u'saleTaxTotal': u'USD46.34',
                                             u'saleTotal': u'USD288.20',
                                             u'segmentPricing': [{u'fareId': u'AWQSZKg4WdIzjGRe9MxuCxp1HWx5y2Qhb7p9up7xqYeM',
                                                                  u'kind': u'qpxexpress#segmentPricing',
                                                                  u'segmentId': u'GFMaEID0stp4343E'},
                                                                 {u'fareId': u'AKV4tAev5WkcuYs1T6b/8AzAKbhBsj2BFQ3lFlCpM1xsjfFdSJDYe71xva4Zg0AAmdUZ3TxLWCkitnpx8KmtCrkvUfeQdDQM30FuH6DmkfY+eYvY98D7uB4CVwp18RKyhJKs9hgYq0dfAx/',
                                                                  u'kind': u'qpxexpress#segmentPricing',
                                                                  u'segmentId': u'G-sLpmxXrlFirVVW'}],
                                             u'tax': [{u'chargeType': u'GOVERNMENT',
                                                       u'code': u'US',
                                                       u'country': u'US',
                                                       u'id': u'US_001',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD18.14'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'AY',
                                                       u'country': u'US',
                                                       u'id': u'AY_001',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD11.20'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'XF',
                                                       u'country': u'US',
                                                       u'id': u'XF',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD9.00'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'ZP',
                                                       u'country': u'US',
                                                       u'id': u'ZP',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD8.00'}]}],
                               u'saleTotal': u'USD288.20',
                               u'slice': [{u'duration': 133,
                                           u'kind': u'qpxexpress#sliceInfo',
                                           u'segment': [{u'bookingCode': u'M',
                                                         u'bookingCodeCount': 1,
                                                         u'cabin': u'COACH',
                                                         u'duration': 133,
                                                         u'flight': {u'carrier': u'B6',
                                                                     u'number': u'906'},
                                                         u'id': u'GFMaEID0stp4343E',
                                                         u'kind': u'qpxexpress#segmentInfo',
                                                         u'leg': [{u'aircraft': u'320',
                                                                   u'arrivalTime': u'2016-07-11T12:03-04:00',
                                                                   u'departureTime': u'2016-07-11T08:50-05:00',
                                                                   u'destination': u'JFK',
                                                                   u'destinationTerminal': u'5',
                                                                   u'duration': 133,
                                                                   u'id': u'LEMJBMf3iT3coS5+',
                                                                   u'kind': u'qpxexpress#legInfo',
                                                                   u'mileage': 737,
                                                                   u'origin': u'ORD',
                                                                   u'originTerminal': u'3',
                                                                   u'secure': True}],
                                                         u'marriedSegmentGroup': u'0'}]},
                                          {u'duration': 168,
                                           u'kind': u'qpxexpress#sliceInfo',
                                           u'segment': [{u'bookingCode': u'U',
                                                         u'bookingCodeCount': 1,
                                                         u'cabin': u'COACH',
                                                         u'duration': 168,
                                                         u'flight': {u'carrier': u'B6',
                                                                     u'number': u'105'},
                                                         u'id': u'G-sLpmxXrlFirVVW',
                                                         u'kind': u'qpxexpress#segmentInfo',
                                                         u'leg': [{u'aircraft': u'E90',
                                                                   u'arrivalTime': u'2016-07-11T22:28-05:00',
                                                                   u'departureTime': u'2016-07-11T20:40-04:00',
                                                                   u'destination': u'ORD',
                                                                   u'destinationTerminal': u'3',
                                                                   u'duration': 168,
                                                                   u'id': u'LKHKN1YMKOBnxeze',
                                                                   u'kind': u'qpxexpress#legInfo',
                                                                   u'mileage': 737,
                                                                   u'origin': u'JFK',
                                                                   u'originTerminal': u'5',
                                                                   u'secure': True}],
                                                         u'marriedSegmentGroup': u'1'}]}]},
                              {u'id': u'394f2mM2ryTQs7DAQNSBLU001',
                               u'kind': u'qpxexpress#tripOption',
                               u'pricing': [{u'baseFareTotal': u'USD241.86',
                                             u'fare': [{u'basisCode': u'MH4ADEN',
                                                        u'carrier': u'B6',
                                                        u'destination': u'NYC',
                                                        u'id': u'AWQSZKg4WdIzjGRe9MxuCxp1HWx5y2Qhb7p9up7xqYeM',
                                                        u'kind': u'qpxexpress#fareInfo',
                                                        u'origin': u'CHI'},
                                                       {u'basisCode': u'UI7ABEN5',
                                                        u'carrier': u'B6',
                                                        u'destination': u'CHI',
                                                        u'id': u'AKV4tAev5WkcuYs1T6b/8AzAKbhBsj2BFQ3lFlCpM1xsjfFdSJDYe71xva4Zg0AAmdUZ3TxLWCkitnpx8KmtCrkvUfeQdDQM30FuH6DmkfY+eYvY98D7uB4CVwp18RKyhJKs9hgYq0dfAx/',
                                                        u'kind': u'qpxexpress#fareInfo',
                                                        u'origin': u'NYC',
                                                        u'private': True}],
                                             u'fareCalculation': u'CHI B6 JFK 146.98MH4ADEN B6 CHI 94.88UI7ABEN5 USD 241.86 END ZP ORD JFK XT 18.14US 8.00ZP 11.20AY 9.00XF ORD4.50 JFK4.50',
                                             u'kind': u'qpxexpress#pricingInfo',
                                             u'latestTicketingTime': u'2016-05-18T23:59-04:00',
                                             u'passengers': {u'adultCount': 1,
                                                             u'kind': u'qpxexpress#passengerCounts'},
                                             u'ptc': u'ADT',
                                             u'saleFareTotal': u'USD241.86',
                                             u'saleTaxTotal': u'USD46.34',
                                             u'saleTotal': u'USD288.20',
                                             u'segmentPricing': [{u'fareId': u'AWQSZKg4WdIzjGRe9MxuCxp1HWx5y2Qhb7p9up7xqYeM',
                                                                  u'kind': u'qpxexpress#segmentPricing',
                                                                  u'segmentId': u'GM-vWt6g5m9rK1GO'},
                                                                 {u'fareId': u'AKV4tAev5WkcuYs1T6b/8AzAKbhBsj2BFQ3lFlCpM1xsjfFdSJDYe71xva4Zg0AAmdUZ3TxLWCkitnpx8KmtCrkvUfeQdDQM30FuH6DmkfY+eYvY98D7uB4CVwp18RKyhJKs9hgYq0dfAx/',
                                                                  u'kind': u'qpxexpress#segmentPricing',
                                                                  u'segmentId': u'G-sLpmxXrlFirVVW'}],
                                             u'tax': [{u'chargeType': u'GOVERNMENT',
                                                       u'code': u'US',
                                                       u'country': u'US',
                                                       u'id': u'US_001',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD18.14'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'AY',
                                                       u'country': u'US',
                                                       u'id': u'AY_001',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD11.20'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'XF',
                                                       u'country': u'US',
                                                       u'id': u'XF',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD9.00'},
                                                      {u'chargeType': u'GOVERNMENT',
                                                       u'code': u'ZP',
                                                       u'country': u'US',
                                                       u'id': u'ZP',
                                                       u'kind': u'qpxexpress#taxInfo',
                                                       u'salePrice': u'USD8.00'}]}],
                               u'saleTotal': u'USD288.20',
                               u'slice': [{u'duration': 129,
                                           u'kind': u'qpxexpress#sliceInfo',
                                           u'segment': [{u'bookingCode': u'M',
                                                         u'bookingCodeCount': 1,
                                                         u'cabin': u'COACH',
                                                         u'duration': 129,
                                                         u'flight': {u'carrier': u'B6',
                                                                     u'number': u'106'},
                                                         u'id': u'GM-vWt6g5m9rK1GO',
                                                         u'kind': u'qpxexpress#segmentInfo',
                                                         u'leg': [{u'aircraft': u'E90',
                                                                   u'arrivalTime': u'2016-07-11T09:09-04:00',
                                                                   u'departureTime': u'2016-07-11T06:00-05:00',
                                                                   u'destination': u'JFK',
                                                                   u'destinationTerminal': u'5',
                                                                   u'duration': 129,
                                                                   u'id': u'LUvOuw0XyHjnUxnd',
                                                                   u'kind': u'qpxexpress#legInfo',
                                                                   u'mileage': 737,
                                                                   u'origin': u'ORD',
                                                                   u'originTerminal': u'3',
                                                                   u'secure': True}],
                                                         u'marriedSegmentGroup': u'0'}]},
                                          {u'duration': 168,
                                           u'kind': u'qpxexpress#sliceInfo',
                                           u'segment': [{u'bookingCode': u'U',
                                                         u'bookingCodeCount': 1,
                                                         u'cabin': u'COACH',
                                                         u'duration': 168,
                                                         u'flight': {u'carrier': u'B6',
                                                                     u'number': u'105'},
                                                         u'id': u'G-sLpmxXrlFirVVW',
                                                         u'kind': u'qpxexpress#segmentInfo',
                                                         u'leg': [{u'aircraft': u'E90',
                                                                   u'arrivalTime': u'2016-07-11T22:28-05:00',
                                                                   u'departureTime': u'2016-07-11T20:40-04:00',
                                                                   u'destination': u'ORD',
                                                                   u'destinationTerminal': u'3',
                                                                   u'duration': 168,
                                                                   u'id': u'LKHKN1YMKOBnxeze',
                                                                   u'kind': u'qpxexpress#legInfo',
                                                                   u'mileage': 737,
                                                                   u'origin': u'JFK',
                                                                   u'originTerminal': u'5',
                                                                   u'secure': True}],
                                                         u'marriedSegmentGroup': u'1'}]}]}]}}
